### ISSUE TITLE
user story 6 - delete button

### ISSUE THREAD

**Issue by Mark-Krensel** [Mark-Krensel/capstone-project#10]
## Value Proposition
As a user, I want to be able to delete an entry, so that I might correct any mistakes I made.

## Description

![Screenshot 2022-10-19 at 12 37 38](https://user-images.githubusercontent.com/104423505/196673388-31e18afd-7880-440b-877f-a96eb8abbd20.png)

## Acception Criteria
- [x] display a delete button on each card
- [x] delete the card, when clicking the button
- [x] delete the entry from the data base

## Tasks
- [x] create delete button
- [x] display delete button
- [x] get ID from clicked entry
- [x] search for id in data base
- [x] delete entry with id in data base
