### ISSUE TITLE
user story 7 - timer

### ISSUE THREAD

**Issue by Mark-Krensel** [Mark-Krensel/capstone-project#11]
## Value Proposition
As a user, I want to track the duration of feeding my baby, so that I can keep track of the feeding durations over time.
## Description

![Screenshot 2022-10-24 at 10 31 37](https://user-images.githubusercontent.com/104423505/197483863-aa2c28c4-275f-4219-a96f-4ec0f633be42.png)

## Acception Criteria
- [x] display start button, when not recording time
- [x] display stop button, while recording
- [x] display recording time, while recording
- [x] start recording, when pressing stop button
- [x] stop recording, when pressing stop button
- [x] display data on a card
## Tasks
- [x] create start/stop button
- [x] create time display field
- [x] display button
- [x] display time
- [x] save time to db
- [x] display data on card
