### ISSUE TITLE
user story 8 - styling & usability

### ISSUE THREAD

**Issue by Mark-Krensel** [Mark-Krensel/capstone-project#18]
## Value Proposition
As a user, I want a nice looking app, so that I enjoy using that app.
## Description
Add more styling to the components and background. Also add icons for nav burger and stopwatch.
## Acception Criteria
- [x] burger menu collapses after clicking anywhere
- [x] app looking pleasant to the eye
- [x] background image
- [x] coherent styling of components, background and header
- [x] fitting color mix
## Tasks
- [x] toggle burger menu when clicking on nav links
- [x] toggle burger menu when clicking anywhere else
- [x] search for background image
- [x] search for /create fitting svgs for burger menu, stopwatch and delete button
- [x] implement background image with ```<Image/>```
- [x] implement svgs
- [x] restyle card and form component
- [x] play around with different colors

**Comment by sebsch1337** [comment]
LGTM :)
