### ISSUE TITLE
user story 1 - display weight & date

### ISSUE THREAD

**Issue by Mark-Krensel** [Mark-Krensel/capstone-project#2]
## Value Proposition
As a user, I want to display weight and date from my baby, so that I can keep track of the weight over time

## Description

<img width="265" alt="Screenshot 2022-10-14 at 16 38 29" src="https://user-images.githubusercontent.com/104423505/195873902-a0cb0885-6315-429d-9812-cd3f788a9e00.png">

## Acception Criteria

- [x] show combined weight and date
- [x] show all entries from example data

## Tasks
- [x] add example data with date and weight
- [x] create card component
- [x] map through array to display all cards

**Comment by F-Kirchhoff** [comment]
This looks already quite good! I have some suggestions to improve it further:
- I think this userstory is quite large, you can for example remove the press button and display the input form directoy above or below the list of measurements
- You can even remove the input first and display one measurement and that is your first userstory
- then you could display a list of mesaurements
- then you can add a form for adding measurements
- then you put the form into the popup 
- so this might be 4 userstories ^^ 

To the Acceptance Criteria
- Please write the explicit effect of the button, not that it is merely interactive
- use more detail in describing what is displayed where

With the tasks:
- please write more detail what tasks need to be done -> create button Component, add button component to home screen, add popup functionality to button etc.
- the more the better ;)
