### ISSUE TITLE
show on weight info on respective page

### ISSUE THREAD

**Issue by Mark-Krensel** [Mark-Krensel/capstone-project#20]
## Value Proposition
As a user, I want to see all my weight input (and only that) in one place, so that I may quickly access that information, without the of searching for it.
## Description

![Screenshot 2022-10-24 at 09 13 08](https://user-images.githubusercontent.com/104423505/199089405-cf3db873-643b-4ab4-beac-feef1b0492ae.png)

## Acception Criteria
- [x] display card with only date & weight
- [x] don't show other information, even if there is more in the db
- [x] show data in descending order, so the newest shows first

## Tasks
- [x] filter array for having only object with respective data
- [x] give cards only data, which is supposed to show
- [x] implement conditional rendering
- [x] exclude delete button from weight page for now
