### ISSUE TITLE
user story 10 - weight graph

### ISSUE THREAD

**Issue by Mark-Krensel** [Mark-Krensel/capstone-project#22]
## Value Proposition
As a user, I want to have a visualisation of my babys weight, so that I may see the weight trend at a quick glance.
## Description

![Screenshot 2022-10-31 at 22 50 21](https://user-images.githubusercontent.com/104423505/199117420-8efb6474-b346-4f0a-8799-f796cd8c9cf5.png)

## Acception Criteria
- [x] show a weight/date graph.
- [x] display all available weight data (for now)
- [x] the data shall be displayed in ascending order, so the latest entry of date should show last.

## Tasks
- [x] install chart.js
- [x] sort data with ```a,b => a.date > b.date```
- [x] define chart input data with ```array.map()```
- [x] implement chart by adding ```<canvas/>``` in  return statement of weight page
- [x] set height, width, style & color from chart

**Comment by F-Kirchhoff** [comment]
hey Mark, please write complete sentences, "ascending order" is not enough. Also please specify the time scope which should be displayed. A month or all time? You can also give your tasks a bit more detail than "implement graph". You might research a bit how to achieve this.

**Comment by Mark-Krensel** [comment]
Thanks for your remarks, you are right of course.  I try to be more specific in the future. I changed it up a bit :)
