### ISSUE TITLE
user story 11 - pool data with the same date

### ISSUE THREAD

**Issue by Mark-Krensel** [Mark-Krensel/capstone-project#24]
## Value Proposition
As a user I want to have all my data from the same date displayed on one card, so that I may have a quick overview of each day.
## Description

![Screenshot 2022-11-02 at 12 45 09](https://user-images.githubusercontent.com/104423505/199481781-5a980212-2844-4fb6-bef7-9362b2c51301.png)

## Acception Criteria
- [x] show all data from same date on one card
- [x] newly added data with existing date shall be incorporated in existing card
- [x] graph displays mean value  of each date (x-axys)

## Tasks
- [x] convert each attribute to an array in db model schema
- [x] when posting new data check if the same date already exists
  - [x] yes: use PATCH http method
  - [x] no: use POST http method
- [x] change card component to read attributes from array instead of single data sets
- [x] change graph to read attributes from array instead of single data sets

**Comment by Roland-Hufnagel** [comment]
I do not understand what kind of graph you are using.

**Comment by Mark-Krensel** [comment]
Hello @Roland-Hufnagel  I integrated the graph into the Wire Frame, so that the user story can be better understood :)

**Comment by Roland-Hufnagel** [comment]
Wow!! Do you use a library for that?

**Comment by Mark-Krensel** [comment]
yes, Im using chart.js
