### ISSUE TITLE
user story 12 - delete single entries

### ISSUE THREAD

**Issue by Mark-Krensel** [Mark-Krensel/capstone-project#26]
## Value Proposition
As user, I want to delete single data points from a data set, so that I may keep the other data points when deleting a single entry.

## Description

![Screenshot 2022-11-07 at 10 30 45](https://user-images.githubusercontent.com/104423505/200278527-3849a4ba-06cc-4811-9f97-70c9f04896c7.png)

## Acception Criteria
- [x] display delete button for single data points
- [x] display this button only on the main page
- [x] don't display this button on the attributes page 

## Tasks
- [x] create new delete button (for single data points)
- [x] render button when path === "/"
- [x] utilise delete function from main page
- [x] give delete function the index of the to-be-deleted data point

**Comment by Roland-Hufnagel** [comment]
Thats a useful userstory. Good description. Have fun on your work!
