### ISSUE TITLE
user story 2 - input weight

### ISSUE THREAD

**Issue by Mark-Krensel** [Mark-Krensel/capstone-project#3]
## Value Proposition
As a user, I want to input my babys weight so that I can keep track of the weight over time with real data.

## Description

![Screenshot 2022-10-17 at 10 20 11](https://user-images.githubusercontent.com/104423505/196125812-54be9bbd-f3e6-4e3a-b201-187471c06486.png)

## Acception Criteria
- [ ] input functionality with numeric value
- [ ] clickable button
- [ ] display input in a new card component

## Tasks
- [ ] create a form 
- [ ] add input field
- [ ] create submit button component
- [ ] on submit: update data in db array

**Comment by philmetscher** [comment]
Hey, nice short user story. Maybe add a description of what the db-array is :)

**Comment by ThomasF85** [comment]
LGTM! Creating a button component (as an actual reusable component) is optional, since you do not have any other use for it now.
