### ISSUE TITLE
user story 3 - input height

### ISSUE THREAD

**Issue by Mark-Krensel** [Mark-Krensel/capstone-project#4]
## Value Proposition
As a user, I want to input my babys height so that I can keep track of the height over time with real data.
## Description

![Screenshot 2022-10-17 at 10 56 07](https://user-images.githubusercontent.com/104423505/196135985-b552ae7f-b495-4cc3-87d8-56492d3bac3a.png)

## Acception Criteria
 - [ ] input functionality with numeric value
 - [ ] clickable button
 - [ ] display input in a new card component

## Tasks
- [ ] create new page 
- [ ] create a form
- [ ] add input field
- [ ] add submit button component
- [ ] on submit: update data in db array with new key:"height" + input value & date.
- [ ] map over db array to display weight & date info in card component

**Comment by CathrinTruchan** [comment]
Nice user story :) 
As you have different pages now, maybe some kind of navigation could be useful?

**Comment by Mark-Krensel** [comment]
baby-steps ;)

**Comment by F-Kirchhoff** [comment]
Hey Mark, why do you need to create a new page for this? It looks like you can add the form into your existing page. Also you could express the tasks in a bit more detail, this might help you later when working on the user story (the last task seems to be a bit inclomplete since your new data might me more than just a key, right?)

**Comment by Mark-Krensel** [comment]
I already have one form on my first page, then i would have two different forms on one page. also i want to display different info on the "height-page".  its supposed to only show the height and date, no weight info there.

**Comment by F-Kirchhoff** [comment]
ok? this might get tricky to structure your app like this. maybe you want to extend the already existing form about another input field for the height? This might be more user friendly when they want to add the infos of one day without going to 4 different pages.
