### ISSUE TITLE
user story 4 - navigation

### ISSUE THREAD

**Issue by Mark-Krensel** [Mark-Krensel/capstone-project#5]
## Value Proposition
As a user, I want to switch between the different pages where a header is displayed , so that I may access all the content of this superb app without getting lost.
## Description

![Screenshot 2022-10-17 at 16 08 54](https://user-images.githubusercontent.com/104423505/196199613-5b4f5b64-020f-4f12-87fd-cddbc0a35083.png)

## Acception Criteria
- [x] display navigation bar
- [x] One nav-button for each page
- [x] display current page in the navigation bar
- [x] display header
- [x] switch to the respective page when clicking the nav-buttons
- [x] navigation bar & header should be displayed in all pages

## Tasks
- [x] create navigation component
- [x] create nav-buttons for each page (li inside ul)
- [x] create header component

**Comment by AHen-C0de** [comment]
Looks good! Nothing to add!

**Comment by philmetscher** [comment]
If u use Button as a Component you could write something like "create each navigation entry as `Button component`".
