### ISSUE TITLE
user story 5 - switch to a data base

### ISSUE THREAD

**Issue by Mark-Krensel** [Mark-Krensel/capstone-project#8]
## Value Proposition
As a User, I want to keep my input data even after closing the session, so that I don't lose my tracking progress.

## Description
use db

## Acception Criteria
- [x] display previous input data, even after refresh
- [x] display previous input data, even when accessing from a different device/browser
- [x] data base gets updated when adding data

## Tasks
- [x] connect mongo db/mongoose
- [x] create file with access credentials. save it so it will not be uploaded to github
- [x] parse data for db
- [x] stringify data for browser reading
- [x] fetch data from db
- [x] save changes in db, when changing/adding data
- [x] update forms onSubmit
- [x] delete fake db in code

**Comment by PhilippWeiss85** [comment]
Hi Mark, looks like clean short and easy to understand story. You could add a little context to your description though.
